### PR TITLE
Adding installation instructions to readme

### LINKED ISSUE #8: Pypi release?
Hey there!

This looks realy handy for a lil project I wanna work on, but I can't find a pypi release for it. The setup.py made me think one exists, but my searching hasn't worked.

Is this lib available on pypi? could it be published there if not?

### PR DESCRIPTION
**Pull request by Deer-Spangle**
Closes #8

### CODE REVIEW

**Comment by StormyDragon** [comment]
Thank you for your contribution; as I mentioned there may be more changes needed to get things to work.

**Comment by Deer-Spangle** [comment]
Yeah! I'll figure that out when I get to trying it out, no worries! 
Thanks again, even if this doesn't work out the box, it'll be a great headstart

**Comment by Deer-Spangle** [comment]
Hmmm, yeah, trying things out and there's a few things in the API that have drifted and could be fixed. 
There's also maybe a couple architectural changes that could be made, maybe?
I'm not sure whether to fix a couple things I come across, and the subset of things that I need, or whether to work on changing more.
Would it be possible to message you somewhere/somehow about it?

**Comment by StormyDragon** [comment]
discord> `StormyDragon` discrim `7500`
(people adding must either be recognizable or let me know beforehand)

**Pull request merged**
